//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoWebService.CalculadoraWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://eam.edu.co/webService", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eam.edu.co/webService", ConfigurationName="CalculadoraWS.CalculadoraWSSoap")]
    public interface CalculadoraWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eam.edu.co/webService/sumar", ReplyAction="*")]
        int sumar(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eam.edu.co/webService/restar", ReplyAction="*")]
        int restar(int num1, int num2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getCalculosResult del espacio de nombres http://eam.edu.co/webService no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://eam.edu.co/webService/getCalculos", ReplyAction="*")]
        ConsumoWebService.CalculadoraWS.getCalculosResponse getCalculos(ConsumoWebService.CalculadoraWS.getCalculosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalculos", Namespace="http://eam.edu.co/webService", Order=0)]
        public ConsumoWebService.CalculadoraWS.getCalculosRequestBody Body;
        
        public getCalculosRequest() {
        }
        
        public getCalculosRequest(ConsumoWebService.CalculadoraWS.getCalculosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCalculosRequestBody {
        
        public getCalculosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalculosResponse", Namespace="http://eam.edu.co/webService", Order=0)]
        public ConsumoWebService.CalculadoraWS.getCalculosResponseBody Body;
        
        public getCalculosResponse() {
        }
        
        public getCalculosResponse(ConsumoWebService.CalculadoraWS.getCalculosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eam.edu.co/webService")]
    public partial class getCalculosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoWebService.CalculadoraWS.ArrayOfString getCalculosResult;
        
        public getCalculosResponseBody() {
        }
        
        public getCalculosResponseBody(ConsumoWebService.CalculadoraWS.ArrayOfString getCalculosResult) {
            this.getCalculosResult = getCalculosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraWSSoapChannel : ConsumoWebService.CalculadoraWS.CalculadoraWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraWSSoapClient : System.ServiceModel.ClientBase<ConsumoWebService.CalculadoraWS.CalculadoraWSSoap>, ConsumoWebService.CalculadoraWS.CalculadoraWSSoap {
        
        public CalculadoraWSSoapClient() {
        }
        
        public CalculadoraWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sumar(int num1, int num2) {
            return base.Channel.sumar(num1, num2);
        }
        
        public int restar(int num1, int num2) {
            return base.Channel.restar(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWebService.CalculadoraWS.getCalculosResponse ConsumoWebService.CalculadoraWS.CalculadoraWSSoap.getCalculos(ConsumoWebService.CalculadoraWS.getCalculosRequest request) {
            return base.Channel.getCalculos(request);
        }
        
        public ConsumoWebService.CalculadoraWS.ArrayOfString getCalculos() {
            ConsumoWebService.CalculadoraWS.getCalculosRequest inValue = new ConsumoWebService.CalculadoraWS.getCalculosRequest();
            inValue.Body = new ConsumoWebService.CalculadoraWS.getCalculosRequestBody();
            ConsumoWebService.CalculadoraWS.getCalculosResponse retVal = ((ConsumoWebService.CalculadoraWS.CalculadoraWSSoap)(this)).getCalculos(inValue);
            return retVal.Body.getCalculosResult;
        }
    }
}
